name: Release Artifacts

on:
  release:
    types: [published]

jobs:
  upload-windows:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4.3.1
        with:
          ref: ${{ github.event.release.tag_name }}
          persist-credentials: false

      - name: Cache dependencies
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4  # v2.9.1

      - name: Build
        run: cargo build --release --locked

      - name: Upload release binary
        env:
          GH_TOKEN: ${{ github.token }}
          TAG: ${{ github.event.release.tag_name }}
        run: gh release upload "$env:TAG" target/release/sidewinder-app.exe
