name: Release Artifacts

on:
  release:
    types: [published]

jobs:
  upload-windows:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          ref: ${{ github.event.release.tag_name }}
          persist-credentials: false

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@cc00eeb07269f3778ca69f08ca1c50f5e1f28eda  # master
        with:
          toolchain: 1.94.1

      - name: Cache dependencies
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4  # v2.9.1

      - name: Build
        run: cargo build --release --locked

      - name: Upload release binary
        env:
          GH_TOKEN: ${{ github.token }}
          TAG: ${{ github.event.release.tag_name }}
        run: gh release upload "$env:TAG" target/release/sideblinder-app.exe
